# Change baseurl before deploy
baseurl = "https://leo-corporation.github.io/Blog/"
languageCode = "en-us"
paginate = 5
title = "Blog | Léo Corporation"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false